### ISSUE TITLE
User can view agents

### ISSUE THREAD

**Issue by kevin-l1** [kevin-l1/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view every single agent in the game, Valorant.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the screen, there is a list of all the Valorant agents organized in rows. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kevin-l1/ajax-project/assets/131307476/b5a32fe3-654c-446e-96e0-c7bd7aa09c20)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header section for the website
- [x] Header should contain the Valorant logo and a tab for agents and bookmarks.
- [x] Create a filter bar that allows you to filter agents based on their roles.
- [x] Filter bar should contain 4 icons in a row for PC, and 2 icons in a row for mobile.
- [x] Create rows that display icons of every single agent in the game.
- [x] Rows should contain 7 icons for PC, and 2 icons for mobile.
- [x] Icons should be clickable and will open a new page showing details of the agent when clicked.
- [x] Agent page should contain a bookmark icon that bookmarks the agent when clicked.
- [x] Clicking the bookmark tab should reveal all bookmarked agents.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
