### ISSUE TITLE
User can filter agents by roles

### ISSUE THREAD

**Issue by kevin-l1** [kevin-l1/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click one of the 4 icons to filter the agents by their roles.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After clicking a 'role' icon, only agents that belong to that specific role are displayed in the agent icon rows.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kevin-l1/ajax-project/assets/131307476/b16fd010-fabd-417e-89df-adb8f136b8d7)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When role icon is clicked, make every other role icon darken
- [x] Display only the agents with the same role as the clicked role icon.
- [x] Agents with a differing role will be hidden.
- [x] When a different role icon is clicked, the previous role icon will darken while the new one will turn white again. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
