### ISSUE TITLE
User can click agent icons to show agent's details

### ISSUE THREAD

**Issue by kevin-l1** [kevin-l1/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the icon of an agent to display a new interface

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When an agent's icon is clicked, the page will change to a screen that shows the details of that agent.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kevin-l1/ajax-project/assets/131307476/be70c63b-7947-42d1-8a78-aa13f57db7d1)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When an icon is clicked, the view swaps to that agent's page
- [x] All other icons should be hidden from view
- [x] In mobile display, the page should show all content in one column.
- [x] With the screen gets larger, the page should split into two columns.
- [x] Clicking the 'agents' tab in the header should bring change the view to the default website display. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
