### ISSUE TITLE
User can bookmark agents

### ISSUE THREAD

**Issue by kevin-l1** [kevin-l1/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the bookmark icon on the top right of an agent's details page to bookmark them.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the bookmark icon is clicked, it will darken and will be saved to the bookmark tab. When the bookmark tab is clicked, it will show a screen that contains all bookmarked agents.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kevin-l1/ajax-project/assets/131307476/5f499df7-b9a9-4992-b886-3585c0546212)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When user clicks bookmark icon on the top-right of an agent's page, it darkens.
- [x] When the bookmark tab is clicked, the bookmark page will be viewable.
- [x] The first row of the page displays 'Bookmarked Agents' .
- [x] The bookmarked agent's icon will appear in the bookmark page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
